export const INITIAL_USERS = [
  {
    id: "user_girlfriend",
    name: "Her",
    role: "girlfriend" as const,
  },
  {
    id: "user_mahesh",
    name: "Mahesh",
    role: "admin" as const,
  },
];

export const INITIAL_POINTS_TRANSACTION = {
  id: "pt_init_10",
  userId: "user_girlfriend",
  amount: 10,
  type: "earned" as const,
  reason: "Starting points",
};

export const INITIAL_REWARDS = [
  {
    id: "rew_1_hug",
    title: "One Hug",
    description: "A proper, long hug. No rush.",
    points: 1,
    emoji: "heart",
    category: "Little Things" as const,
    featured: false,
    active: true,
    fulfillmentInstructions: JSON.stringify([
      "Give a proper, long, cozy hug with no rush.",
    ]),
    sortOrder: 1,
  },
  {
    id: "rew_2_message",
    title: "Sweet Message",
    description: "A message made just for you.",
    points: 2,
    emoji: "mail",
    category: "Little Things" as const,
    featured: false,
    active: true,
    fulfillmentInstructions: JSON.stringify([
      "Write and send a sweet, thoughtful message just for her.",
    ]),
    sortOrder: 2,
  },
  {
    id: "rew_3_snack",
    title: "Favorite Snack",
    description: "I'll get your favorite snack.",
    points: 3,
    emoji: "cookie",
    category: "Treats" as const,
    featured: false,
    active: true,
    fulfillmentInstructions: JSON.stringify([
      "Ask/confirm her craving",
      "Buy the favorite snack",
      "Hand it over with love",
    ]),
    sortOrder: 3,
  },
  {
    id: "rew_4_attention",
    title: "Undivided Attention",
    description: "Your time. My full attention.",
    points: 4,
    emoji: "hands",
    category: "Little Things" as const,
    featured: false,
    active: true,
    fulfillmentInstructions: JSON.stringify([
      "Put phone on silent/away",
      "Dedicate uninterrupted time just for her",
    ]),
    sortOrder: 4,
  },
  {
    id: "rew_5_movie",
    title: "Favorite Movie",
    description: "You choose the movie. I'm watching.",
    points: 5,
    emoji: "movie",
    category: "Experiences" as const,
    featured: false,
    active: true,
    fulfillmentInstructions: JSON.stringify([
      "Let her pick the movie",
      "Prepare comfy seating and snacks",
      "Watch together with zero complaints",
    ]),
    sortOrder: 5,
  },
  {
    id: "rew_6_food",
    title: "Food or Drink Choice",
    description: "You pick what we're having.",
    points: 6,
    emoji: "drink",
    category: "Treats" as const,
    featured: false,
    active: true,
    fulfillmentInstructions: JSON.stringify([
      "Her choice of restaurant, takeout, or cooked meal",
      "Place order or make it happen",
    ]),
    sortOrder: 6,
  },
  {
    id: "rew_7_bike",
    title: "Bike Lesson",
    description: "I'll teach you how to ride a bike.",
    points: 7,
    emoji: "bike",
    category: "Experiences" as const,
    featured: true,
    active: true,
    fulfillmentInstructions: JSON.stringify([
      "Pick a sunny, quiet day",
      "Prepare bikes and safety gear",
      "Patient, fun beginner lesson with zero pressure",
    ]),
    sortOrder: 7,
  },
  {
    id: "rew_8_princess",
    title: "Princess Treatment Evening",
    description: "An evening planned around you.",
    points: 8,
    emoji: "crown",
    category: "Special" as const,
    featured: false,
    active: true,
    fulfillmentInstructions: JSON.stringify([
      "Plan the full evening itinerary",
      "Treat her like royalty from start to finish",
    ]),
    sortOrder: 8,
  },
  {
    id: "rew_9_date",
    title: "Special Date",
    description: "A date made just for us.",
    points: 9,
    emoji: "rose",
    category: "Special" as const,
    featured: false,
    active: true,
    fulfillmentInstructions: JSON.stringify([
      "Choose a romantic location/vibe",
      "Dress up and spend meaningful time together",
    ]),
    sortOrder: 9,
  },
  {
    id: "rew_10_rules",
    title: "Your Day, Your Rules",
    description: "One playful day where you get to choose.",
    points: 10,
    emoji: "sparkles",
    category: "Special" as const,
    featured: true,
    active: true,
    fulfillmentInstructions: JSON.stringify([
      "Agree on the designated day",
      "She makes all the calls all day long",
    ]),
    sortOrder: 10,
  },
];
